version: 0.2
env:
  variables:
    APP_NAME: "angular-agoralabs-site-cicd-pipeline"
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo install process started
      - npm install --force
      - npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - ng build --configuration=production
  post_build:
    commands:
      - echo build process finished, we should uplload to S3 now and invalidate cloudfront cache
      - cd dist/Omnivus
      - ls -la
      - aws s3 sync . s3://www.agoralabs.org --delete
      - aws cloudfront create-invalidation --distribution-id E1GIT1T3RS7J28 --paths "/*"